default: &default
  adapter: mysql2
  reconnect: true
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_bin
  host: <%= ENV["DATABASE_HOSTNAME"] %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  port: <%= ENV["DATABASE_PORT"] %>

development:
  <<: *default
  database: <%= ENV["DATABASE_NAME"] %>

test:
  <<: *default
  database: <%= ENV["DATABASE_NAME"] %>

production:
  <<: *default
  database: <%= ENV["DATABASE_NAME"] %>
